### ISSUE TITLE
Tickets working weirdly

### ISSUE THREAD

**Issue by vermium** [greys-bots/form-fox#40]
Everyone can see the open ticket, I think only a specific role and the user should see it

**Comment by selenated** [comment]
The permissions for tickets should be based on the category that they belong to! Though right now there are some issues with tickets that might be causing that

I would double check that the category you have set up only allows your specific role to view channels in it, instead of being public to everyone

**Comment by selenated** [comment]
Hi! Are you still having this issue?

**Comment by selenated** [comment]
Closing for now, feel free to reopen this if you're still having issues
