### ISSUE TITLE
postGreSQL

### ISSUE THREAD

**Issue by shockbs** [greys-bots/form-fox#7]
Hi!
Can I have the tutorial link of setting up posygresql with this project? or just tell me here the steps, please.

**Comment by selenated** [comment]
Hiya, honestly this question is best answered by googling something like "postgres install [operating system]"- here are some links though:
- [postgres download page](https://www.postgresql.org/download/)
- [tutorial site - installation page](https://www.postgresqltutorial.com/postgresql-getting-started/)
- [ubuntu-specific tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-postgresql-on-ubuntu-20-04-quickstart)

Once this is installed, you'll want to make sure the server's running (might need some more look-ups). Then you can open a terminal and enter `psql` to open up the shell, and do whatever you need to in there, like create a new database to use or create a new user with a password/change the password of the default user. Just make sure you update the `.env` with all the info

All that said, we can't really offer much more support for postgres here on the repo since it isn't really part of the focus here. If you need more help, feel free to join the support server listed in the readme and we can try to figure everything out :3  
In the meantime I'll go ahead and close this to keep things tidy
